title: EAG Docs
description: Documentation and Procedures for the Experimental Astrophysics Group @ SSL
theme: just-the-docs

url: https://eag.marvinlin.space

aux_links:
  Space Sciences Lab: https://www.ssl.berkeley.edu/
  Source Repository: https://github.com/marvinlinn/eag-documentation

heading_anchors: true

callouts:
  note:
    title: Note
    color: blue
  highlight:
    color: yellow